
SECRET_KEY = '123456790'

# DATABASE_FILE = 'python'
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.sqlite3'

SQLALCHEMY_ECHO = True

SECURITY_PASSWORD_HASH = "pbkdf2_sha512"
SECURITY_PASSWORD_SALT = "thisissecret"

SECURITY_LOGIN_URL = "/login"
SECURITY_LOGOUT_URL = "/logout"

SECURITY_POST_LOGIN_VIEW = "/index"
SECURITY_POST_LOGOUT_VIEW = "/login"

SECURITY_REGISTERABLE = False
SECURITY_SEND_REGISTER_EMAIL = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
